services:
  - type: web
    name: rescue-animal-social-media-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config wsgi.py Project.app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1